apiVersion: apps/v1
kind: Deployment
metadata:
  name: geonetwork
  labels:
    app: geonetwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonetwork
  template:
    metadata:
      name: geonetwork
      labels:
        app: geonetwork 
    spec:
      containers:
      - name: daaas-geonetwork
        image: ktjaco/daaas-geonetwork
        env:
          - name: POSTGRES_DB_USERNAME
            value: "docker"
          - name: POSTGRES_DB_PASSWORD
            value: "password"
          - name: POSTGRES_DB_HOST
            value: "localhost"
        ports:
          - containerPort: 8080
        selector:
          matchLabels:
            app: geonetwork
